addSbtPlugin("com.github.gseitz"  % "sbt-release"           % "1.0.8")
addSbtPlugin("com.jsuereth"       % "sbt-pgp"               % "1.1.0")
addSbtPlugin("io.spray"           % "sbt-revolver"          % "0.9.1")
addSbtPlugin("org.scalariform"    % "sbt-scalariform"       % "1.8.0")
addSbtPlugin("org.xerial.sbt"     % "sbt-sonatype"          % "2.3")
